name: Check PHP syntax errors
on:
  push:
    branches: [ main ]
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: overtrue/phplint@9.5.4
          with:
            path: .
            options: --exclude=*.md
